___________________________________________________________________________________________________________
# Introduction to Pytorch 
### (based on the [60 min blitz Deep Learning with Pytorch] (https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html) )

## 1. Tensors
## 2. A Gentle Introduction to ``torch.autograd``
## 3. Neural Networks
## 4. Train a Classifier

_____________________________________________________________________________________________________

PyTorch is a Python-based scientific computing package serving two broad purposes:

- A replacement for NumPy to use the power of GPUs and other accelerators.
- An automatic differentiation library that is useful to implement neural networks.

Goal of this tutorial:

 - Understand PyTorch’s Tensor library and neural networks at a high level.
 - Train a small neural network to classify images

### NOTE:
The 4 sessions can be run independently, so if you feel confident with the first sessions you can quickly cover them. However, for the last session *4. Train a Classifier* you are expected to complete some empty cells to successfully train and test your `net`. 
_____________________________________________________________________________________________________

# 1. Tensors
--------------------------------------------

Tensors are a specialized data structure that are very similar to arrays
and matrices. In PyTorch, we use tensors to encode the inputs and
outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on
GPUs or other specialized hardware to accelerate computing. If you’re familiar with ndarrays, you’ll
be right at home with the Tensor API. If not, follow along in this quick
API walkthrough.


In [1]:
import torch
import numpy as np

In [2]:
print(torch.__version__)

2.2.0+cu121


### Tensor Initialization


Tensors can be initialized in various ways. Take a look at the following examples:

**Directly from data**

Tensors can be created directly from data. The data type is automatically inferred.



In [5]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print (x_data)

tensor([[1, 2],
        [3, 4]])


**From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa - see *bridge-to-np-label*).



In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print (x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.



In [7]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5824, 0.9410],
        [0.4936, 0.3383]]) 



**With random or constant values:**

*shape* is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.



In [8]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5318, 0.7494, 0.5981],
        [0.6641, 0.3822, 0.4531]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Tensor Attributes


Tensor attributes describe their shape, datatype, and the device on which they are stored.



In [9]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Tensor Operations


Over 100 tensor operations, including transposing, indexing, slicing,
mathematical operations, linear algebra, random sampling, and more are
comprehensively described [here](https://pytorch.org/docs/stable/torch.html).

Try out some of the operations from the list.
If you're familiar with the NumPy API, you'll find the Tensor API a breeze to use.



**Standard numpy-like indexing and slicing:**



In [4]:
tensor = torch.ones(4, 4)
print(tensor)
tensor[:,2] = 0
tensor[:,3] = 5
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 0., 5.],
        [1., 1., 0., 5.],
        [1., 1., 0., 5.],
        [1., 1., 0., 5.]])


**Joining tensors** You can use *torch.cat* to concatenate a sequence of tensors along a given dimension.
See also [torch.stack] (https://pytorch.org/docs/stable/generated/torch.stack.html),
another tensor joining operation that is subtly different from *torch.cat*.



In [8]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)

tensor([[1., 1., 0., 5.],
        [1., 1., 0., 5.],
        [1., 1., 0., 5.],
        [1., 1., 0., 5.],
        [1., 1., 0., 5.],
        [1., 1., 0., 5.],
        [1., 1., 0., 5.],
        [1., 1., 0., 5.],
        [1., 1., 0., 5.],
        [1., 1., 0., 5.],
        [1., 1., 0., 5.],
        [1., 1., 0., 5.]])


**Multiplying tensors**



In [17]:
print(tensor)
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor([[1., 1., 0., 5.],
        [1., 1., 0., 5.],
        [1., 1., 0., 5.],
        [1., 1., 0., 5.]])
tensor.mul(tensor) 
 tensor([[ 1.,  1.,  0., 25.],
        [ 1.,  1.,  0., 25.],
        [ 1.,  1.,  0., 25.],
        [ 1.,  1.,  0., 25.]]) 

tensor * tensor 
 tensor([[ 1.,  1.,  0., 25.],
        [ 1.,  1.,  0., 25.],
        [ 1.,  1.,  0., 25.],
        [ 1.,  1.,  0., 25.]])


This computes the matrix multiplication between two tensors



In [10]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")  #.T transpose
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[ 7.,  7.,  0., 35.],
        [ 7.,  7.,  0., 35.],
        [ 7.,  7.,  0., 35.],
        [ 7.,  7.,  0., 35.]]) 

tensor @ tensor.T 
 tensor([[27., 27., 27., 27.],
        [27., 27., 27., 27.],
        [27., 27., 27., 27.],
        [27., 27., 27., 27.]])


**In-place operations**
Operations that have a `_` suffix are in-place. For example: `x.copy_(y)`, ``x.t_()``, will change ``x``.



In [19]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 1., 0., 5.],
        [1., 1., 0., 5.],
        [1., 1., 0., 5.],
        [1., 1., 0., 5.]]) 

tensor([[ 6.,  6.,  5., 10.],
        [ 6.,  6.,  5., 10.],
        [ 6.,  6.,  5., 10.],
        [ 6.,  6.,  5., 10.]])


In [20]:
print(tensor, "\n")
tensor.sub_(3)
print(tensor)

tensor([[ 6.,  6.,  5., 10.],
        [ 6.,  6.,  5., 10.],
        [ 6.,  6.,  5., 10.],
        [ 6.,  6.,  5., 10.]]) 

tensor([[3., 3., 2., 7.],
        [3., 3., 2., 7.],
        [3., 3., 2., 7.],
        [3., 3., 2., 7.]])


In [21]:
print(tensor, "\n")
tensor.t_()
print(tensor)

tensor([[3., 3., 2., 7.],
        [3., 3., 2., 7.],
        [3., 3., 2., 7.],
        [3., 3., 2., 7.]]) 

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [2., 2., 2., 2.],
        [7., 7., 7., 7.]])


In [23]:
print(tensor, "\n")
tensor.copy_(2)
print(tensor)

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]]) 

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])


### NOTE

n-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss
     of history. Hence, their use is discouraged.</p></div>



**Bridge to NumPy**

Tensor to NumPy array




In [24]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.



In [28]:
t.add_(2)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([6., 6., 6., 6., 6.])
n: [6. 6. 6. 6. 6.]


NumPy array to Tensor



In [30]:
n = np.ones(5)
t = torch.from_numpy(n)
print(t)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


Changes in the NumPy array reflects in the tensor.



In [32]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
n: [3. 3. 3. 3. 3.]
